# -*- coding: utf-8 -*-
"""streamlit_app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_uL4YgpdDYxzHHNWPj3FHiPInS_WUEt
"""

!pip install streamlit
import streamlit as st

st.title("Token15")
st.write("Bienvenue sur mon application Streamlit")